### ISSUE TITLE
How to use this project using mp3 files of spoken dialogs

### ISSUE THREAD

**Issue by KIC** [usc-sail/mica-gender-from-audio#5]
I have followed the readme and made a text file pointing to a list of mp3 files which contain spoken dialogs in various languages which I want to label with gender.

I am getting the error:

```

Using configuration :
nj=2
feats_flag="n"
wavs_flag="y"
sad_overlap=0.0
gender_overlap=0
uniform_seg_len=1
only_vad=0

 >>>> CREATING WAV FILES <<<< 
bash_scripts/create_wav_files.sh: line 33: 1 % 0 : division by 0 (error token is "0 ")
[mp3float @ 0x565405cffc80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 0x565405cffc80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 0x565405cffc80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 0x565405cffc80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 0x565405cffc80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
Unable to extract all .wav files, exiting...
 >>>> EXTRACTING FEATURES FOR SAD <<<< 
Usage: split_scp.pl [--utt2spk=<utt2spk_file>] in.scp out1.scp out2.scp ... 
 or: split_scp.pl -j num-jobs job-id [--utt2spk=<utt2spk_file>] in.scp [out.scp]
 ... where 0 <= job-id < num-jobs. at ./split_scp.pl line 64.
cat: results//features/feats.scp: No such file or directory
 >>>> GENERATING SAD LABELS <<<< 
cat: results//features/feats.scp: No such file or directory
generate_gender_pred.sh: line 142: 1 % 0: division by 0 (error token is "0")
 >>>> EXTRACTING VGGISH EMBEDDINGS <<<< 
WARNING:tensorflow:From /home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/audioset_scripts/vggish_model.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[{{node vggish_load_pretrained/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/extract_vggish_feats.py", line 139, in <module>
    tf.app.run()
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/extract_vggish_feats.py", line 75, in main
    vggish_slim.load_vggish_slim_checkpoint(sess, checkpoint)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/audioset_scripts/vggish_slim.py", line 128, in load_vggish_slim_checkpoint
    saver.restore(session, checkpoint_path)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/audioset_scripts/vggish_model.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node vggish_load_pretrained/RestoreV2 (defined at /home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/audioset_scripts/vggish_slim.py:127) ]]

Caused by op 'vggish_load_pretrained/RestoreV2', defined at:
  File "/home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/extract_vggish_feats.py", line 139, in <module>
    tf.app.run()
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/extract_vggish_feats.py", line 75, in main
    vggish_slim.load_vggish_slim_checkpoint(sess, checkpoint)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/audioset_scripts/vggish_slim.py", line 127, in load_vggish_slim_checkpoint
    saver = tf.train.Saver(vggish_vars, name='vggish_load_pretrained')
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/xxx/sources/priavte/mica-gender-from-audio/.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

DataLossError (see above for traceback): Unable to open table file /home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/audioset_scripts/vggish_model.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node vggish_load_pretrained/RestoreV2 (defined at /home/xxx/sources/priavte/mica-gender-from-audio/python_scripts/audioset_scripts/vggish_slim.py:127) ]]

 >>>> PREDICTING GENDER SEGMENTS <<<< 
 >>>> GENDER SEGMENTS PER-MOVIE CAN BE FOUND IN results//GENDER/timestamps <<<< 
```

**Comment by KIC** [comment]
the wav files are there. It very much looks like the features can not be extracted: `run.pl: job failed, log is in results//features/log/make_fbank_feats.1.log` but the mentioned log file das not exist. not even teh folder "features" exists
